apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2024-04-07T20:42:50Z"
  generation: 4
  labels:
    app: sretest
  name: sretest
  namespace: default
  resourceVersion: "6494"
  uid: 712a0dee-5b20-4e07-875c-284d8429b802
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sretest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-04-07T21:27:26Z"
      creationTimestamp: null
      labels:
        app: sretest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/application
                operator: In
                values:
                - sretest
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: sretest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-07T21:13:01Z"
    lastUpdateTime: "2024-04-07T21:13:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-07T21:13:01Z"
    lastUpdateTime: "2024-04-07T21:27:28Z"
    message: ReplicaSet "sretest-6cb756dc7c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-07T20:42:50Z"
  name: sretest-service
  namespace: default
  resourceVersion: "4694"
  uid: fecea8ba-0a73-4a1e-aa98-e14ec3d6390e
spec:
  clusterIP: 10.97.146.6
  clusterIPs:
  - 10.97.146.6
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30851
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sretest
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}